# ================================================================
# Makefile
# export LD_LIBRARY_PATH=$(pwd)/bin
# ================================================================

APP = cobol-project-maker
MAIN = $(APP).cbl
CPYBOOKS = 
TESTS_ARGS = coco-project
_dll = trimright create-makefile create-cobolfile 

include ../mk/common.mk

